# Revision History
Showing only substantive changes from 5.0 to 5.1 here.[^REV5]

[^REV5]: Refer to earlier releases for prior changes.

## Introduction
Updated copyrights and minor editorial changes to the document introduction.

## Electrical Standards
2.1 Wiring
: Paragraph 2.b, changed 16 VAC to 16 VDC.

2.3 Accessory Power
: Paragraph 1, changed 16 VAC to 16 VDC with footnote.


2.4.1 Wiring Color Code Specification ES 1.0
: Changed 16 VAC 1, 2 to 16 VDC Black-Positive, White-Negative (Ground).

