meta-json: {"title":"![](media/image1.png)Module Specifications"}
title: NGM Module Specifications

**Adapted from NMRA & Piedmont Division Standards**

**NMRA Compatible**[^Intro1]

Release 5.1

July, 2020

© 2020 NGM Club, Inc.

Copyright 2020 NGM Club, Inc. (with portions copyright 1990, 1994 NMRA Piedmont Division)

[^Intro1]: NMRA compliant modules may be easily integrated into **NGM** layouts with some minor adaptations to the electrical connections.

