# Cars and Equipment

The requirements for rolling stock which will be used during a specific
setup of the layout may be determined in advance by the setup
coordinator. If equipment being used on the layout is performing in a
manner deemed by the setup coordinator to not be sufficiently reliable,
he/she may order it removed from the layout until the condition has been
corrected.

# Coupler Type: Recommended Practice

It is recommended that the coupler type be a **KADEE** style coupler.
All couplers will be checked for free movement and the centering spring
should be fully functional.

***EXCEPTION:*** Trains that operate as a single unit, such as passenger
trains, may utilize any coupler type available, since interaction with
other cars will not occur.

# Coupler Height: Recommended Practice

All cars will be checked on the test track prior to placing them on the
layout. The test track will have **KADEE** coupler height gauges to
verify proper coupler height. Cars not meeting the proper height may not
be approved for operation on the layout. The test track will be provided
by the club.

# Car Weight: Recommended Practice

Cars should be weighted according to the **NMRA** recommended practice
**RP-20.1.**

Portions of **RP-20.1** are reprinted here:


| SCALE | Initial Weight | Additional Weight Per Inch of Body Length |
| :--- | :--- | :--- |
| HO  | 1 ounce | + ½ ounce |

To figure the optimum weight of a given car, take measurements of the
car with a standard ruler. Multiply the length of the car in inches by
.5 and then add 1. This will be the optimum weight of the car. If the
car is light weight add the difference in lead weights until desired
weight is achieved.

*EXAMPLE:*

A 50 ft car weighs *2* ounces and the car is roughly *7"* long. The
optimum weight is figured as follow: 7x.5 (*3.5*) ,+1 (*4.5*), -2
(*2.5*) The difference between the initial car weight (*2*) and the
optimum weight (*4.*5) is *2.5* and it is the amount of weight to add to
the car.

