# AWG

AWG refers to "American Wire Gauge". It is a standard that defines
electrical wire sizes by a numerical value. The word "***gauge***" is
commonly used when referring to a wire size.

**For the technical types:**, 14 gauge wire is 1.628 mm in diameter and
has the ability to conduct 17 amps of electrical current while only
having 2 ohms or resistance per 1000 feet.

# Auxiliary Track

Auxiliary lines serve as an optional third mainline when possible. When
used as a mainline, it must be installed with the same standards as the
other mainlines. An auxiliary track is always parallel to the mainline
at a 2 ½" center from mainline \#2 and is also called Mainline \#3. When
used as a siding, branch line standards apply and it may not be
considered as a third mainline if it deviates from the mainline
standard.

# Branch Lines

These lines are optional on all modules. They must conform to all
**NGM** electrical and interface standards. They must also be insulated
from the mainline if a local analog throttle is to be used while the
mainline is active.

# Bridge Track

A connecting, removable track section used to join the tracks between
modules. The interface area has been sized to allow standard sectional
track parts to be inserted between modules. *(Also known as an Interface
Track.)*

# Center Spacing

The distance between the centerlines of parallel tracks.

# Conforming Modules

Modules that are freely interchangeable in every way with all other
conforming modules built to these standards. Conformity shall be
determined by the **NGM** Conformance Committee.

# DCC

**Digital Command Control (DCC)**. The **NGM** standard incorporates
**NMRA** approved standards for **DCC** operation . **DCC** allows for
independent selection and control of engines by sending commands over
the rails to miniature microprocessors installed in the engine bodies.
The **NGM** electrical standard requires a telephone style jack to
connect the hand-held controller.

# East End

This is the right-hand end of the module as seen from the front (the
normal viewing side)

# West End

This is the left-hand end of the module as seen from the front (the
normal viewing side.)

# Interface Area

Any portion of the module within 3" from the East and West ends of the
module. *(See the Interface Area diagram.)* The Interface Area is
considerably restricted by the **NMRA** and **NGM** standards to ensure
that modules are interchangeable and operations are smooth. The **NMRA**
standard defines the Interface Area to be 4½" vs. the 3" adopted by
**NGM**.

# Mainline Track

The standard defines the mainline as two tracks running the length of
the module, not including the interface area, that provide eastbound and
westbound operation of trains. The mainline is restricted to 5" and 7"
centerlines from the front of the module (in the interface area) with
some optional variations. The mainline also has strict radius, grade and
turnout restrictions to ensure smooth operation.

# Mated Set

Any group of modules in which the individual modules *cannot* be used
separately for some reason. Mated Sets typically consist of modules that
do not conform to our interface standards between themselves, but
conform to the interface standards at both ends of the set.

A variation of a mated set is a group of modules that fully conform to
our interface standards but are designed to be joined together due to
scene continuity or optional interface area track connections that
provide multi module continuity. *(Commonly seen in intermodal yard
modules.)*

# Module

A module is a portable section of a table-like frame work which is one
part of a large group of similar modules that when assembled together
forms a large and fully operating model railroad. They are built by
individuals as part of a home layout or specifically for interfacing
with others in a large setup. All are built to a set of standards that
allow each unit to interface exactly with other units anywhere in the
overall system. A module may be a single frame or a set of frames that
interface with other modules in a standard manner but that may deviate
from the interface standard between ends (*see Interface Area.*) By
being portable, they may be disassembled-assembled for transporting to
conventions or public displays. Many clubs are formed for the specific
purpose of building module layouts as space for permanent layouts is
hard to find and very expensive when available. **NGM** is such a club.

# Non-Conforming Module

Modules that are not built to these standards (in either track
arrangement or electrical wiring methods) and therefore not directly
compatible with the system as outlined here.

# Non-Interface Area

Any portion of the module not within the interface area. Restrictions
within the non-interface area are minimal, although extreme variations
in grade, turn radius, and track gauge could render the module
undesirable.

# Route Convention

The southern most mainline (mainline \#1) runs eastward and the next
parallel mainline runs westward. The auxiliary mainline direction is not
defined. **NOTE:** The viewing side of the module is the south side.

