# Diagrams


## D-1 NGM Track Standard (Recommended)

## D-2 Leg Construction (Recommended.)

## D-3 Basic Frame Construction (Recommended.)

## D-4 Corner Module Dimensions

**Showing exterior frame dimensions and track placement only. Consult NGM for construction details.**

## D-5 Wiring Diagram for Branchlines

** No longer applicable - Removed

## D-6 Wiring Configuration Diagram

**Showing wire color code and connector configurations.**


