# Diagrams


## D-1 NGM Track Standard (Recommended)

**Also showing NMRA Track Standard (for reference only.)**

[Insert image.]

![](media/image1.wmf)

## D-2 Leg Construction (Recommended.)

[Insert image.]

![](media/image3.wmf)

## D-3 Basic Frame Construction (Recommended.)

[Insert image.]

![](media/image4.wmf)

## D-4 Corner Module Dimensions

**Showing exterior frame dimensions and track placement only. Consult NGM for construction details.**

[Insert image.]

![](media/image5.wmf)

## D-5 Wiring Diagram for Branchlines

**Allowing analog throttle operation for branchline.**

[Insert image.]

![](media/image6.wmf)

## D-6 Wiring Configuration Diagram

**Showing wire color code and pin numbers.**

[Insert image.]

![](media/image7.wmf)

