# Diagrams


## D-1 NGM Track Standard
This diagram illustrates the recommended track layout.

![Track Standard](Drawings\D-1 Track Standard.png "Track Standard")

## D-2 Leg Construction
This diagram illustrates the recommended method for making module legs.

![Leg Construction](Drawings\D-2 Leg Construction.png "Leg Construction")

## D-3 Basic Frame Construction
This diagram illustrates the recommended method for making a standard, straight module.

![Basic Frame Construction](Drawings\D-3 Basic Frame.png "Basic Frame Construction")

![Frame Clamp](Drawings\D-3.2 Frame Clamp.png "Frame Clamp")

## D-4 Corner Module Dimensions
Showing exterior frame dimensions and track placement only. Consult NGM for construction details.

![Corner Module](Drawings\D-4 Corner Module.png "Corner Module")

## D-5 Wiring Configuration Diagram
Showing wire color code and connector configurations.

![Wiring Configuration](Drawings\D-6 Wiring Configuration.png "Wiring Configuration")

