# Framework: General

The specifications for module sizes are relatively strict. The following
describes the minimum requirements and recommended practices for module
framework construction. Modules will be checked annually to ensure
conformance to specifications following the **NGM** Module Compliance
Audit Form. Conforming modules will display a dated sticker which will
provide sufficient proof of compliance.

As of this revision, the **NGM** standards committee has not approved
the use of transition modules to allow for the inclusion of
non-conforming modules.

# Framework: Requirements

For consistency with existing modules, it is recommended the module
frame sides and ends will be made with 1" x 4" (^3^/~4~" x 3½" finished
[^11]) lumber such as common pine. It shall be straight, solid and free
of knots. It shall be sanded smooth prior to finishing and painting. All
visible framework must be painted with Ace Hardware Forest Green
interior latex paint (or equivalent.) Some provision must be provided
for hanging NGM provided decorative curtain or skirting.[^12]

Modules are joined by 3" C-clamps. Provision must be made to clamp to
any other module whose side frame is a standard 1" x 4". Two clamps are
required for each module end and none will be provided by the club. Two
clamps are required to allow front to back track alignment.

[^11]: Note that if Tortoise© switch machines are to be installed
    standard 1" x 4" lumber will not provide adequate depth to protect
    them from damage.

[^12]: A ¾" Velcro© strip (hook side) is recommended.

## Frame Dimensions

| Dimension | Min. | Max. |
| :--- | :---: | :---: |
| **Leg Height** | N/A | Adjust with eye bolt to reach 40" at rail [^13] 
                                                    
   *See Diagram **D-2** (Leg Construction)* |
| **Length** | 24" | 96" (in 24" increments) |
| **Depth** | 18" | 36" |
| **Height** | 3 ½" | N/A |

Frame corners must be square

[^13]: Must be adjustable from 39" to 41".

## Framework: Recommended Practices

It is recommended that the frame pieces be joined with screws and glue.
It is also recommended that the gluing be done on the inside of the
framework to eliminate glue residue from marring the appearance of the
frame exterior.

If a handle is attached to the module, it should be done on the north
side so that it is not seen during shows. The legs should be removable
and have a T-nut or threaded insert and eye bolt installed on the floor
side to allow for rail height adjustments.

