# Revision History


## Rev 5.0
Showing only substantive changes from 4.1 to 5.0 here.[^REV5]

[^REV5]: Refer to earlier releases for prior changes.

### Introduction
* Updated copyrights and minor editorial changes to the document introduction.

### Track Work
* 1.0 Track Work Standards
    + Set Backs, East/West Ends reduced from 1 ½" to 0".

    + Centerline Spacing: Eliminated duplication of Interface and Non-Interface areas.

    + Interface Track Length: Deleted as no longer necessary.

    + Increased vertical clearance from 3" to 3.5".

### Rolling Stock
* Removed the **Rolling Stock** section as it is more appropriate in an Operations Guideline document.

### Electrical Standards
* 2.0.1 Removed references to NMRA and old NGM standards. Replace Pin \# with Anderson Housing number. Changed 18VAC to 16VAC.

* 2.0.2 Removed references to NMRA and old NGM standards. Updated to reflect the use of Anderson connectors.

* 2.0.3 Removed references to NMRA and old NGM standards. Removed Orientation line.

* 2.1.1 Rewritten for Anderson connectors instead of ATA 9-pin connector.

* 2.1.2 Rewritten for Anderson connectors instead of ATA 9-pin connector.

* 2.1.3.1 Rewritten for Anderson connectors instead of ATA 9-pin connector.

* 2.1.3.2 Rewritten for Anderson connectors instead of ATA 9-pin connector.

* 2.1.3.4 Removed.

* 2.1.4 Removed reference to branch line analog isolation.

* 2.1.5 Changed 18 VAC to 16 VAC.

### Framework
* 3.1 Added requirement to enable attachment of skirting on inside facing frame.

### Command Control Reference
* Removed the **Command Control** section as it is better suited to a general reference document.

