# Revision History


## Rev 3.0


## Rev 4.0

Chart NGME 1.0: Changed recommended wire colors.

Chart NGME 1.1: Changed plug and socket.

Chart NGME 1.2: Removed requirement for AC power strip.

Paragraph 2.1.1: Changed bus connection from "through module" to
"backbone" method.

Paragraph 2.1.2: Changed description of Main Electrical Bus.

Paragraph 2.1.3.1: Modified to reflect change in connector.

Paragraph 2.1.3.2: Modified to reflect change in connector.

Paragraph 2.1.3.3: Removed.

Added Paragraph 2.1.6

## Rev 4.1

Diagram text formatting

Updated Table of Contents

No content modifications

## Rev 5.0
[Add all changes from 4.1 to 5.0 here.]

### Introduction
* Updates and minor editorial changes to the document introduction.

### Rolling Stock
* Removed the Rolling Stock section as it is more appropriate in an Operations Guideline document.

### Electrical Standards
* 2.0.1 Removed references to NMRA and old NGM standards. Replace Pin \# with Anderson Housing number. Changed 18VAC to 16VAC.
* 2.0.2 Removed references to NMRA and old NGM standards. Updated to reflect the use of Anderson connectors.
* 2.0.3 Removed references to NMRA and old NGM standards. Removed Orientation line.
* 2.1.1 Rewritten for Anderson connectors instead of ATA 9-pin connector.
* 2.1.2 Rewritten for Anderson connectors instead of ATA 9-pin connector.
* 2.1.3.1 Rewritten for Anderson connectors instead of ATA 9-pin connector.
* 2.1.3.2 Rewritten for Anderson connectors instead of ATA 9-pin connector.
* 2.1.3.4 Removed.
* 2.1.4 Removed reference to branch line analog isolation.
* 2.1.5 Changed 18 VAC to 16 VAC.

### Command Control Reference
* Removed the Command Control section as it is better suited to a general reference document.

