# General

The scenery design, style, colors and details are all optional. Each
module has the option of being a stand alone diorama or belonging to a
set of modules that make up a mated set. The club will not mandate
scenery styles nor scenery contents. As a general guideline, a clear
majority of **NGM** modelers have followed a modern, late 1960's to 90's
theme.

# Sky Board

Each module will have a sky board or backboard that extends 14" above
the rear side rail. It should be 1/8" shorter than the module on each
end to avoid interference with adjoining modules. The sky board may be
permanently attached but it is recommended that it be removable for ease
of transportation. *(See diagram **D-3** for placement.)* The sky board
must be painted on both sides. **NGM** recommends the use of Sherwin
Williams Universe Blue (or equivalent) for the front of the sky board.
Paint the back of the sky board with the same green paint used for the
frame *(refer to section **3.1**.)*

I'm adding another paragraph.

