# Track Work


## NGM Module Track Work Standards Sheets
The **NGM** Standards are derived from the **Piedmont Division Standards** and have been modified to suit the operating conditions of **NGM**.

### Track Work Standards TWS 1
|  **Item**  | **NGM Standard** |
| :---------- | :---------- |
| Type | Hand laid or Commercial |
| **Size** ||
| Mainline | HO Code 100 |
| Auxiliary | HO Code 100 |
| Other | HO Code 70 (minimum) |
| **Set Backs** ||
| East/West Ends | 0" |
| Mainline \#1[^TW1] | 5" |
| Mainline \#2 | 7" |
| Auxiliary | 9 ½" |
| **Track Centerline Spacing** ||
| Mainlines \#1 \& \#2 | 2" |
| Auxiliary to Main \#2 | 2 ½" minimum |
| Curves | 2 ½" minimum[^TW2] |
| Elevation | 40" from floor to top of mainline railheads within interface area.[^TW3]  |

[^TW1]: From front edge of module.
[^TW2]: At all points except transition to 2" approaching parallel track.
[^TW3]: Adjustable from 39" to 41".

### Track Work Standards TWS 2
|  **Item**  | **NGM Standard** |
| :---------- | :---------- |
| **Horizontal Clearances**[^TW4] | Minimum |
| Straight Track | 1 1/32" |
| Curved Track | 1 ¼" [^TW5] |
| Vertical Clearance | 3" |
| Parallel Tangent Track | 3" |
| **Grades** | Maximum |
| Mainline | 3% |
| Auxiliary | 3% |
| Branch Line | 3% |
| **Turnouts** | Minimum Size |
| Main | \#6[^TW6] |
| Auxiliary | \#6 |
| Branch Line | \#4 |
| **Curve Radius on Corner Module**[^TW7] | Minimum |
| Mainline | 37" |
| Auxiliary | 35" |
| Branch Line | 32" |
| **Curve Radius on Straight Module** | Minimum | 
| Mainline | 32" |
| Auxiliary | 29 ½" |
| Branch Line | 18" |
| **Other** ||
| Uncouplers | Permanent magnet may not be used on mainlines. |

[^TW4]: Horizontal clearances are from track center. Refer to NMRA Standards S-7 and S-8, Revised Aug. 1982.
[^TW5]: Refer to S-8, Class Ia for track radius of 32".
[^TW6]: Use of PECO medium is acceptable.
[^TW7]: Diagram D-4 shows the revised NGM Corner Module standard showing minimum curve radius.

## Track Work Reference
The following track work information applies to all **NGM** modules. They apply regardless of size or type.

### Track Work: Requirements
To be compatible with existing **NGM** modules, it is a requirement that one adhere to the **NGM** Standard.

### Switch Machine
Manual ground throws or electrical switch machines may be used to control switch position. The only requirement is that all switch devices shall positively lock the switch machine in either position when set.

### Mainlines
Two mainlines shall be required, located as shown in diagram **D-1**. The club supports modules that provide an auxiliary mainline but it is not required.

### Module Interface Tracks
**NGM** Track End Standard negates the need for interface track.

## Track Work: Recommended Practices


### Uncouplers
**Kadee's** \#307 (switched) electromagnetic uncoupler (or equivalent) is acceptable on the mainline tracks, so long as it is properly installed and does not interfere with the passage of trains.

### Through Tracks
The minimum required number of through tracks is 2. An auxiliary through track should be considered to allow for a third mainline. When providing information about your module, please provide the auxiliary track type, that is, Mainline \#3 or branch line. Providing for the third mainline remains optional.

### Transition
Use of code 83 rail or smaller should have a 2 ½" transition track before meeting with mainline code 100 rail. (*Transition should not occur at a switch joint*.)

### Switches
Switches with positive locking action are preferred over the more common slide action switches. This style mechanism is most commonly found on switches made by **PECO**. If a switch without positive lock is installed, it is highly recommended that it be driven by a switch machine that resists accidental movement; for example, a Tortoise© motor driven switch machine.

