# Track Work


## NGM Module Track Work Standards Sheets

The **NGM** Standards are derived from the **Piedmont Division Standards** and have been modified to suit the operating conditions of **NGM**.

### Track Work Standards

|  Item  | NGM Std. |
|  :----  |  :---:  |
|  Type | Hand laid or Commercial |
| Size | |
| Mainline | HO Code 100 |
| Auxiliary | HO Code 100 |
| Other | HO Code 100 |
| Set Backs | |
|  :----  |  :---:  |
| *East/West Ends* | 3" |
| *From Front* | | |
| Mainline \#1 | 5" |
| Mainline \#2 | 7" |
| Auxiliary | 9 ½" |
| Centerline Spacing | |
|  :----  |  :---:  |
| *Interface Area* | |
| Mainlines 1 & 2 | 2" |
| Auxiliary | 2" |
| *Non Interface Area* | |
| Mainlines 1 & 2 | 2" min. |
| Auxiliary | 2 ½" min. |
| *Curves* | 2 ½" track centerline at all points except transition to 2" approaching parallel track |
| Elevation | 40" from floor to top of mainline railheads within interface area [^1] |
| Clearances | |
|  Horizontal | |
|   Straight Track | 1 1/32" |
|   Curved Track | 1 1/4" [^2] |
|  Vertical | 3" |
| Interface Track Length | N/A |
| Parallel Tangent Track (Min.) | 3" |
| Grade (Max.) | |
|  Mainline | 3% |
|  Auxiliary | 3% |
|  Branch Line | 3% |
| Turnouts (Min. size) | |
|  Mainline | \#6 [^3] |
|  Auxiliary | \#6 [^3] |
|  Branch Line | \#4 |
| Curve Radius (Min.) | |
|  Corner Module | |
|   Mainline | 37" |
|   Auxiliary | 35" |
|   Branch Line | 32" |
|  Straight Module | | 
|   Mainline | 32" |
|   Auxiliary | 29 ½" |
|   Branch Line | 18" |
|   "Industrial" | N/A |
| Uncouplers | |
|  Permanent Magnet | Not for use on mainlines |

## Track Work Reference

The following track work information applies to all **NGM** modules.  They apply regardless of size or type.

### Track Work: Requirements

To be compatible with existing **NGM** modules, it is a requirement that one adhere to **either** the **NMRA** Standard **or** the **NGM** Standard.

### Switch Machine

Manual ground throws or electrical switch machines may be used to control switch position. The only requirement is that all switch devices shall positively lock the switch machine in either position when set.

### Mainlines

Two mainlines shall be required, located as shown in diagram **D-1**. The club is supportive of modules that provide an auxiliary mainline but it is not required.

### Module Interface Tracks

**NGM** Track End Standard negates the need for interface track.

## Track Work: Recommended Practices


### Uncouplers

**Kadee's** \#307 (switched) electromagnetic uncoupler (or equivalent) is acceptable on the mainline tracks, so long as it is properly installed and does not interfere with the passage of trains.

### Through Tracks

The minimum required number of through tracks is 2. An auxiliary through track should be considered to allow for a third mainline. When providing information about your module, please be sure to provide the auxiliary track type, that is, Mainline \#3 or branch line. Providing for the third mainline remains optional.

### Transition

Use of code 83 rail or smaller should have a 2 ½" transition track before meeting with mainline code 100 rail. (*Transition should not occur at a switch joint*.)

### Switches

Switches with positive locking action are preferred over the more common slide action switches. This style mechanism is most commonly found on switches made by **PECO**. If a switch without positive lock is installed, it is highly recommended that it be driven by a switch machine that resists accidental movement; for example, a Tortoise© motor driven switch machine.

[^1]: Adjustable from 39" to 41"
[^2]: Horizontal clearances are from track center.
[^3]: Refer to **S-8**, Class Ia for track radius of 32".
[^4]: Use of PECO medium is acceptable.

