# 1. Trackwork
- Main section review assigned to Duane.
- Needs updating to refer to the new Track End Spec with comment to interface older style modules.  Updated track ends are recommended and encouraged.
- Inconsistency re uncouplers.
- Diagram D-1 needs to be updated to show Track Ends.
- Compare NMRA track clearance spec. to NGM needs and update accordingly (double-stacks and auto-racks).
- Eliminate references to NMRA standards where possible.

# 2. Electrical
-Main section review and edit assigned to Rob.
- Plug and socket spec needs updating.  
- Diagrams D-5 and D-6 needs to be updated.
- Eliminate references to NMRA standards and obsolete NGM standards where possible.

# 3. Frame Work
- Update re club providing clamps
- Verify paint colors (fascia green and skyboard blue)

# 4. Scenery
- No update

# 5. Rolling Stock
- Move to separate document.

# 6. Command Control
- Move entire section to separate document.

# Diagrams
- All diagram updates assigned to Walt.
- D-1 Update diagram to reflect current practice.
- D-2 Leave as-is.
- D-3 Update diagram to reflect current wiring standard.
- D-4 Engineering review, decide and update accordingly.
- D-5 Remove (no longer supported).
- D-6 Update diagram to reflect current wiring standard.
- D-X Add diagrams of M and J connections.

# Definitions
- Decide later which definitions need to stay and which to remove or edit.

