# Revision History
Showing only substantive changes from 5.1 to 5.2 here.[^REV5]

[^REV5]: Refer to earlier releases for prior changes.

## Electrical Standards
3.1 Wiring
: Paragraph 2.b, changed 16 VAC to 12 VDC.

3.3 Accessory Power
: Paragraph 1, changed 16 VAC to 12 VDC and removed footnote.


3.4.1 Wiring Color Code Specification ES 1.0
: Changed 16 VDC 1, 2 to 12 VDC Black-Positive, White-Negative (Ground).

